#!/usr/bin/env python3
"""
build_bundle.py — generates card_components_bundle.js
Run: python3 build_bundle.py

Bundles only the assets currently needed by the card composer
(Character - Standard, traits, icons, and the fonts used by card_composer.css).
When other card types are enabled, add their patterns to INCLUDE_PATTERNS.
"""

import base64
import glob
import os

BASE   = os.path.join(os.path.dirname(__file__), 'card_components')
OUTPUT = os.path.join(os.path.dirname(__file__), 'card_components_bundle.js')

MIME = {
    '.png':  'image/png',
    '.svg':  'image/svg+xml',
    '.ttf':  'font/truetype',
    '.otf':  'font/opentype',
    '.woff': 'font/woff',
    '.woff2':'font/woff2',
}

# Only the fonts referenced in card_composer.css
FONTS = [
    'fonts/Font - Card Name - Bayformers TFTCGName Regular.ttf',
    'fonts/Font - Ability Text - Gotham Narrow-Book.ttf',
    'fonts/Font - Keywords - Gotham Narrow-Medium.otf',
    'fonts/Font - Explanatio Text - Gotham Narrow-Book Italic.otf',
    'fonts/Font - Stats - Armada Condensed Bold.otf',
    'fonts/Font - Character Mode - OpenSans SemiCondensed Bold.ttf',
    'fonts/Font - Traits - OpenSans SemiBold.ttf',
    'fonts/Font - Wave, Credits - OpenSans Bold.ttf',
    'fonts/Font - Stratagem Target - OpenSans SemiCondensed MediumItalic.ttf',
    'fonts/Font - Cybertonian - Giedi Ancient Autobot.ttf',
]

def collect_files():
    files = []

    # Character - Standard PNGs
    for path in sorted(glob.glob(os.path.join(BASE, 'character', 'Character - Standard - *.png'))):
        files.append(path)

    # All trait PNGs
    for path in sorted(glob.glob(os.path.join(BASE, 'traits', '*.png'))):
        files.append(path)

    # All icon PNGs
    for path in sorted(glob.glob(os.path.join(BASE, 'icons', '*.png'))):
        files.append(path)

    # Stamp SVG(s)
    for path in sorted(glob.glob(os.path.join(BASE, 'stamp', '*.svg'))):
        files.append(path)

    # Specific fonts only
    for rel in FONTS:
        path = os.path.join(BASE, rel)
        if os.path.exists(path):
            files.append(path)
        else:
            print(f'  WARNING: font not found: {rel}')

    return files

def encode(path):
    ext  = os.path.splitext(path)[1].lower()
    mime = MIME.get(ext, 'application/octet-stream')
    with open(path, 'rb') as f:
        data = base64.b64encode(f.read()).decode('ascii')
    return f'data:{mime};base64,{data}'

def main():
    files = collect_files()
    print(f'Bundling {len(files)} files...')

    entries = []
    for path in files:
        key = os.path.relpath(path, BASE).replace(os.sep, '/')
        val = encode(path)
        # JSON-escape the key and wrap value in quotes
        escaped_key = key.replace('"', '\\"')
        entries.append(f'"{escaped_key}":"{val}"')
        print(f'  + {key}')

    bundle = (
        '// Auto-generated by build_bundle.py — do not edit manually\n'
        '// Regenerate: python3 build_bundle.py\n'
        'const CARD_COMPONENTS_BUNDLE = {' + ','.join(entries) + '};\n'
    )

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(bundle)

    size_mb = os.path.getsize(OUTPUT) / 1024 / 1024
    print(f'\nDone. {len(files)} assets → {OUTPUT}')
    print(f'Bundle size: {size_mb:.1f} MB')

if __name__ == '__main__':
    main()
